apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.webApp.name }}
spec:
  tls:
  - hosts:
      - {{ .Values.webApp.ingress.host }}
    secretName: tls-secret
  rules:
  - host: {{ .Values.webApp.ingress.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.webApp.name }}
              port:
                number: {{ .Values.webApp.service.targetPort  }}