//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CombatAnalysis.App.Localizations.Resources.DamageDoneScore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CombatAnalysis.App.Localizations.Resources.DamageDoneScore.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average damage.
        /// </summary>
        public static string AverageDamage {
            get {
                return ResourceManager.GetString("AverageDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average DPS.
        /// </summary>
        public static string AverageDPS {
            get {
                return ResourceManager.GetString("AverageDPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average ILvl.
        /// </summary>
        public static string AverageItemLevel {
            get {
                return ResourceManager.GetString("AverageItemLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string DamageDone {
            get {
                return ResourceManager.GetString("DamageDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS.
        /// </summary>
        public static string DPS {
            get {
                return ResourceManager.GetString("DPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit value.
        /// </summary>
        public static string EditValue {
            get {
                return ResourceManager.GetString("EditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. damage.
        /// </summary>
        public static string MinDamage {
            get {
                return ResourceManager.GetString("MinDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. DPS.
        /// </summary>
        public static string MinDPS {
            get {
                return ResourceManager.GetString("MinDPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total damage.
        /// </summary>
        public static string TotalDamage {
            get {
                return ResourceManager.GetString("TotalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total DPS.
        /// </summary>
        public static string TotalDPS {
            get {
                return ResourceManager.GetString("TotalDPS", resourceCulture);
            }
        }
    }
}
