//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CombatAnalysis.App.Localizations.Resources.DamageTakenScore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CombatAnalysis.App.Localizations.Resources.DamageTakenScore.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average damage taken.
        /// </summary>
        public static string AverageDamageTaken {
            get {
                return ResourceManager.GetString("AverageDamageTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average DTPS.
        /// </summary>
        public static string AverageDTPS {
            get {
                return ResourceManager.GetString("AverageDTPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average ILvl.
        /// </summary>
        public static string AverageItemLevel {
            get {
                return ResourceManager.GetString("AverageItemLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage taken.
        /// </summary>
        public static string DamageTaken {
            get {
                return ResourceManager.GetString("DamageTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTPS.
        /// </summary>
        public static string DTPS {
            get {
                return ResourceManager.GetString("DTPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit value.
        /// </summary>
        public static string EditValue {
            get {
                return ResourceManager.GetString("EditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. damage taken.
        /// </summary>
        public static string MinDamageTaken {
            get {
                return ResourceManager.GetString("MinDamageTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. DTPS.
        /// </summary>
        public static string MinDTPS {
            get {
                return ResourceManager.GetString("MinDTPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total damage taken.
        /// </summary>
        public static string TotalDamageTaken {
            get {
                return ResourceManager.GetString("TotalDamageTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total DTPS.
        /// </summary>
        public static string TotalDTPS {
            get {
                return ResourceManager.GetString("TotalDTPS", resourceCulture);
            }
        }
    }
}
