//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CombatAnalysis.App.Localizations.Resources.HealDoneScore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CombatAnalysis.App.Localizations.Resources.HealDoneScore.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average heal.
        /// </summary>
        public static string AverageHeal {
            get {
                return ResourceManager.GetString("AverageHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average HPS.
        /// </summary>
        public static string AverageHPS {
            get {
                return ResourceManager.GetString("AverageHPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average ILvl.
        /// </summary>
        public static string AverageItemLevel {
            get {
                return ResourceManager.GetString("AverageItemLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit value.
        /// </summary>
        public static string EditValue {
            get {
                return ResourceManager.GetString("EditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal.
        /// </summary>
        public static string HealDone {
            get {
                return ResourceManager.GetString("HealDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPS.
        /// </summary>
        public static string HPS {
            get {
                return ResourceManager.GetString("HPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. heal.
        /// </summary>
        public static string MinHeal {
            get {
                return ResourceManager.GetString("MinHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. HPS.
        /// </summary>
        public static string MinHPS {
            get {
                return ResourceManager.GetString("MinHPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total heal.
        /// </summary>
        public static string TotalHeal {
            get {
                return ResourceManager.GetString("TotalHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total HPS.
        /// </summary>
        public static string TotalHPS {
            get {
                return ResourceManager.GetString("TotalHPS", resourceCulture);
            }
        }
    }
}
