// <auto-generated />
using System;
using CombatAnalysis.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CombatAnalysis.DAL.Migrations
{
    [DbContext(typeof(CombatParserContext))]
    partial class CombatParserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.Boss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Difficult")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<long>("Health")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Boss");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Difficult = 3,
                            GameId = 1395,
                            Health = 130841100L,
                            Name = "Каменные стражи",
                            Size = 10
                        },
                        new
                        {
                            Id = 2,
                            Difficult = 5,
                            GameId = 1395,
                            Health = 235513980L,
                            Name = "Каменные стражи",
                            Size = 10
                        },
                        new
                        {
                            Id = 3,
                            Difficult = 3,
                            GameId = 1390,
                            Health = 152647950L,
                            Name = "Фэн Проклятый",
                            Size = 10
                        },
                        new
                        {
                            Id = 4,
                            Difficult = 5,
                            GameId = 1390,
                            Health = 209345760L,
                            Name = "Фэн Проклятый",
                            Size = 10
                        },
                        new
                        {
                            Id = 5,
                            Difficult = 3,
                            GameId = 1434,
                            Health = 117756990L,
                            Name = "Душелов Гара'джал",
                            Size = 10
                        },
                        new
                        {
                            Id = 6,
                            Difficult = 5,
                            GameId = 1434,
                            Health = 179252307L,
                            Name = "Душелов Гара'джал",
                            Size = 10
                        },
                        new
                        {
                            Id = 7,
                            Difficult = 3,
                            GameId = 1436,
                            Health = 174454800L,
                            Name = "Призрачные короли",
                            Size = 10
                        },
                        new
                        {
                            Id = 8,
                            Difficult = 5,
                            GameId = 1436,
                            Health = 261682200L,
                            Name = "Призрачные короли",
                            Size = 10
                        },
                        new
                        {
                            Id = 9,
                            Difficult = 3,
                            GameId = 1500,
                            Health = 294392475L,
                            Name = "Элегон",
                            Size = 10
                        },
                        new
                        {
                            Id = 10,
                            Difficult = 5,
                            GameId = 1500,
                            Health = 339750723L,
                            Name = "Элегон",
                            Size = 10
                        },
                        new
                        {
                            Id = 11,
                            Difficult = 3,
                            GameId = 1407,
                            Health = 314018640L,
                            Name = "Воля императора",
                            Size = 10
                        },
                        new
                        {
                            Id = 12,
                            Difficult = 5,
                            GameId = 1407,
                            Health = 471027960L,
                            Name = "Воля императора",
                            Size = 10
                        },
                        new
                        {
                            Id = 13,
                            Difficult = 3,
                            GameId = 1409,
                            Health = 213968815L,
                            Name = "Вечные защитники",
                            Size = 10
                        },
                        new
                        {
                            Id = 14,
                            Difficult = 5,
                            GameId = 1409,
                            Health = 344082093L,
                            Name = "Вечные защитники",
                            Size = 10
                        },
                        new
                        {
                            Id = 15,
                            Difficult = 3,
                            GameId = 1505,
                            Health = 174454800L,
                            Name = "Цулон",
                            Size = 10
                        },
                        new
                        {
                            Id = 16,
                            Difficult = 5,
                            GameId = 1505,
                            Health = 279127680L,
                            Name = "Цулон",
                            Size = 10
                        },
                        new
                        {
                            Id = 17,
                            Difficult = 3,
                            GameId = 1506,
                            Health = 138168195L,
                            Name = "Лэй Ши",
                            Size = 10
                        },
                        new
                        {
                            Id = 18,
                            Difficult = 5,
                            GameId = 1506,
                            Health = 301457900L,
                            Name = "Лэй Ши",
                            Size = 10
                        },
                        new
                        {
                            Id = 19,
                            Difficult = 3,
                            GameId = 1431,
                            Health = 184704020L,
                            Name = "Ша Страха",
                            Size = 10
                        },
                        new
                        {
                            Id = 20,
                            Difficult = 5,
                            GameId = 1431,
                            Health = 544037304L,
                            Name = "Ша Страха",
                            Size = 10
                        },
                        new
                        {
                            Id = 21,
                            Difficult = 3,
                            GameId = 1507,
                            Health = 174454800L,
                            Name = "Императорский визирь Зор'лок",
                            Size = 10
                        },
                        new
                        {
                            Id = 22,
                            Difficult = 5,
                            GameId = 1507,
                            Health = 218068500L,
                            Name = "Императорский визирь Зор'лок",
                            Size = 10
                        },
                        new
                        {
                            Id = 23,
                            Difficult = 3,
                            GameId = 1504,
                            Health = 150467265L,
                            Name = "Повелитель клинков Та'як",
                            Size = 10
                        },
                        new
                        {
                            Id = 24,
                            Difficult = 5,
                            GameId = 1504,
                            Health = 196261650L,
                            Name = "Повелитель клинков Та'як",
                            Size = 10
                        },
                        new
                        {
                            Id = 25,
                            Difficult = 3,
                            GameId = 1463,
                            Health = 218068500L,
                            Name = "Гаралон",
                            Size = 10
                        },
                        new
                        {
                            Id = 26,
                            Difficult = 5,
                            GameId = 1463,
                            Health = 290759446L,
                            Name = "Гаралон",
                            Size = 10
                        },
                        new
                        {
                            Id = 27,
                            Difficult = 3,
                            GameId = 1498,
                            Health = 270404940L,
                            Name = "Повелитель ветров Мел'джарак",
                            Size = 10
                        },
                        new
                        {
                            Id = 28,
                            Difficult = 5,
                            GameId = 1498,
                            Health = 588784950L,
                            Name = "Повелитель ветров Мел'джарак",
                            Size = 10
                        },
                        new
                        {
                            Id = 29,
                            Difficult = 3,
                            GameId = 1499,
                            Health = 218068500L,
                            Name = "Ваятель янтаря Ун'сок",
                            Size = 10
                        },
                        new
                        {
                            Id = 30,
                            Difficult = 5,
                            GameId = 1499,
                            Health = 340186860L,
                            Name = "Ваятель янтаря Ун'сок",
                            Size = 10
                        },
                        new
                        {
                            Id = 31,
                            Difficult = 3,
                            GameId = 1501,
                            Health = 196261650L,
                            Name = "Великая императрица Шек'зир",
                            Size = 10
                        },
                        new
                        {
                            Id = 32,
                            Difficult = 5,
                            GameId = 1501,
                            Health = 307476585L,
                            Name = "Великая императрица Шек'зир",
                            Size = 10
                        },
                        new
                        {
                            Id = 33,
                            Difficult = 3,
                            GameId = 1577,
                            Health = 207601212L,
                            Name = "Джин'рок Разрушитель",
                            Size = 10
                        },
                        new
                        {
                            Id = 34,
                            Difficult = 5,
                            GameId = 1577,
                            Health = 317507736L,
                            Name = "Джин'рок Разрушитель",
                            Size = 10
                        },
                        new
                        {
                            Id = 35,
                            Difficult = 3,
                            GameId = 1575,
                            Health = 357632340L,
                            Name = "Хорридон",
                            Size = 10
                        },
                        new
                        {
                            Id = 36,
                            Difficult = 5,
                            GameId = 1575,
                            Health = 654205500L,
                            Name = "Хорридон",
                            Size = 10
                        },
                        new
                        {
                            Id = 37,
                            Difficult = 3,
                            GameId = 1570,
                            Health = 299538888L,
                            Name = "Совет старейшин",
                            Size = 10
                        },
                        new
                        {
                            Id = 38,
                            Difficult = 5,
                            GameId = 1570,
                            Health = 470330152L,
                            Name = "Совет старейшин",
                            Size = 10
                        },
                        new
                        {
                            Id = 39,
                            Difficult = 3,
                            GameId = 1565,
                            Health = 179999841L,
                            Name = "Тортос",
                            Size = 10
                        },
                        new
                        {
                            Id = 40,
                            Difficult = 5,
                            GameId = 1565,
                            Health = 319999818L,
                            Name = "Тортос",
                            Size = 10
                        },
                        new
                        {
                            Id = 41,
                            Difficult = 3,
                            GameId = 1578,
                            Health = 263317712L,
                            Name = "Мегера",
                            Size = 10
                        },
                        new
                        {
                            Id = 42,
                            Difficult = 5,
                            GameId = 1578,
                            Health = 342297774L,
                            Name = "Мегера",
                            Size = 10
                        },
                        new
                        {
                            Id = 43,
                            Difficult = 3,
                            GameId = 1573,
                            Health = 244236720L,
                            Name = "Цзи-Кунь",
                            Size = 10
                        },
                        new
                        {
                            Id = 44,
                            Difficult = 5,
                            GameId = 1573,
                            Health = 366355080L,
                            Name = "Цзи-Кунь",
                            Size = 10
                        },
                        new
                        {
                            Id = 45,
                            Difficult = 3,
                            GameId = 1572,
                            Health = 261682200L,
                            Name = "Дуруму Позабытый",
                            Size = 10
                        },
                        new
                        {
                            Id = 46,
                            Difficult = 5,
                            GameId = 1572,
                            Health = 392523300L,
                            Name = "Дуруму Позабытый",
                            Size = 10
                        },
                        new
                        {
                            Id = 47,
                            Difficult = 3,
                            GameId = 1574,
                            Health = 218068500L,
                            Name = "Изначалий",
                            Size = 10
                        },
                        new
                        {
                            Id = 48,
                            Difficult = 5,
                            GameId = 1574,
                            Health = 258193104L,
                            Name = "Изначалий",
                            Size = 10
                        },
                        new
                        {
                            Id = 49,
                            Difficult = 3,
                            GameId = 1576,
                            Health = 80999797L,
                            Name = "Темный Анимус",
                            Size = 10
                        },
                        new
                        {
                            Id = 50,
                            Difficult = 5,
                            GameId = 1576,
                            Health = 288000023L,
                            Name = "Темный Анимус",
                            Size = 10
                        },
                        new
                        {
                            Id = 51,
                            Difficult = 3,
                            GameId = 1559,
                            Health = 119937675L,
                            Name = "Кон Железный",
                            Size = 10
                        },
                        new
                        {
                            Id = 52,
                            Difficult = 5,
                            GameId = 1559,
                            Health = 155700909L,
                            Name = "Кон Железный",
                            Size = 10
                        },
                        new
                        {
                            Id = 53,
                            Difficult = 3,
                            GameId = 1560,
                            Health = 219812670L,
                            Name = "Небесные сестры",
                            Size = 10
                        },
                        new
                        {
                            Id = 54,
                            Difficult = 5,
                            GameId = 1560,
                            Health = 628036200L,
                            Name = "Небесные сестры",
                            Size = 10
                        },
                        new
                        {
                            Id = 55,
                            Difficult = 3,
                            GameId = 1579,
                            Health = 329283435L,
                            Name = "Лэй Шэнь",
                            Size = 10
                        },
                        new
                        {
                            Id = 56,
                            Difficult = 5,
                            GameId = 1579,
                            Health = 580498347L,
                            Name = "Лэй Шэнь",
                            Size = 10
                        });
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.Combat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BossId")
                        .HasColumnType("int");

                    b.Property<int>("CombatLogId")
                        .HasColumnType("int");

                    b.Property<int>("DamageDone")
                        .HasColumnType("int");

                    b.Property<int>("DamageTaken")
                        .HasColumnType("int");

                    b.Property<string>("DungeonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnergyRecovery")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FinishDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HealDone")
                        .HasColumnType("int");

                    b.Property<bool>("IsReady")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWin")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Combat");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.CombatAura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuraCreatorType")
                        .HasColumnType("int");

                    b.Property<int>("AuraType")
                        .HasColumnType("int");

                    b.Property<int>("CombatId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("FinishTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stacks")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CombatAura");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.CombatLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CombatsInQueue")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsReady")
                        .HasColumnType("bit");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberReadyCombats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CombatLog");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.CombatPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageItemLevel")
                        .HasColumnType("float");

                    b.Property<int>("CombatId")
                        .HasColumnType("int");

                    b.Property<int>("DamageDone")
                        .HasColumnType("int");

                    b.Property<int>("DamageTaken")
                        .HasColumnType("int");

                    b.Property<int>("HealDone")
                        .HasColumnType("int");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResourcesRecovery")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CombatPlayer");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.CombatPlayerPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CombatId")
                        .HasColumnType("int");

                    b.Property<int>("CombatPlayerId")
                        .HasColumnType("int");

                    b.Property<double>("PositionX")
                        .HasColumnType("float");

                    b.Property<double>("PositionY")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("CombatPlayerPosition");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.DamageDone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CombatPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DamageType")
                        .HasColumnType("int");

                    b.Property<bool>("IsPeriodicDamage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPet")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSingleTarget")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTargetBoss")
                        .HasColumnType("bit");

                    b.Property<string>("Spell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DamageDone");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.DamageDoneGeneral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageValue")
                        .HasColumnType("float");

                    b.Property<int>("CastNumber")
                        .HasColumnType("int");

                    b.Property<int>("CombatPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("CritNumber")
                        .HasColumnType("int");

                    b.Property<double>("DamagePerSecond")
                        .HasColumnType("float");

                    b.Property<bool>("IsPet")
                        .HasColumnType("bit");

                    b.Property<int>("MaxValue")
                        .HasColumnType("int");

                    b.Property<int>("MinValue")
                        .HasColumnType("int");

                    b.Property<int>("MissNumber")
                        .HasColumnType("int");

                    b.Property<string>("Spell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DamageDoneGeneral");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.DamageTaken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Absorbed")
                        .HasColumnType("int");

                    b.Property<int>("ActualValue")
                        .HasColumnType("int");

                    b.Property<int>("Blocked")
                        .HasColumnType("int");

                    b.Property<int>("CombatPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DamageTakenType")
                        .HasColumnType("int");

                    b.Property<bool>("IsPeriodicDamage")
                        .HasColumnType("bit");

                    b.Property<int>("Mitigated")
                        .HasColumnType("int");

                    b.Property<int>("RealDamage")
                        .HasColumnType("int");

                    b.Property<int>("Resisted")
                        .HasColumnType("int");

                    b.Property<string>("Spell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DamageTaken");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.DamageTakenGeneral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualValue")
                        .HasColumnType("int");

                    b.Property<double>("AverageValue")
                        .HasColumnType("float");

                    b.Property<int>("CastNumber")
                        .HasColumnType("int");

                    b.Property<int>("CombatPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("CritNumber")
                        .HasColumnType("int");

                    b.Property<double>("DamageTakenPerSecond")
                        .HasColumnType("float");

                    b.Property<int>("MaxValue")
                        .HasColumnType("int");

                    b.Property<int>("MinValue")
                        .HasColumnType("int");

                    b.Property<int>("MissNumber")
                        .HasColumnType("int");

                    b.Property<string>("Spell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DamageTakenGeneral");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.HealDone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CombatPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAbsorbed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCrit")
                        .HasColumnType("bit");

                    b.Property<int>("Overheal")
                        .HasColumnType("int");

                    b.Property<string>("Spell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HealDone");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.HealDoneGeneral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageValue")
                        .HasColumnType("float");

                    b.Property<int>("CastNumber")
                        .HasColumnType("int");

                    b.Property<int>("CombatPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("CritNumber")
                        .HasColumnType("int");

                    b.Property<double>("HealPerSecond")
                        .HasColumnType("float");

                    b.Property<int>("MaxValue")
                        .HasColumnType("int");

                    b.Property<int>("MinValue")
                        .HasColumnType("int");

                    b.Property<string>("Spell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HealDoneGeneral");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Faction")
                        .HasColumnType("int");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.PlayerDeath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CombatPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("LastHitSpell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LastHitValue")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlayerDeath");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.PlayerParseInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BossId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("CombatPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("DamageEfficiency")
                        .HasColumnType("int");

                    b.Property<int>("HealEfficiency")
                        .HasColumnType("int");

                    b.Property<int>("SpecId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlayerParseInfo");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.PlayerStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("CombatPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Crit")
                        .HasColumnType("int");

                    b.Property<int>("Dodge")
                        .HasColumnType("int");

                    b.Property<int>("Expertise")
                        .HasColumnType("int");

                    b.Property<int>("Faction")
                        .HasColumnType("int");

                    b.Property<int>("Haste")
                        .HasColumnType("int");

                    b.Property<int>("Hit")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Parry")
                        .HasColumnType("int");

                    b.Property<int>("Spirit")
                        .HasColumnType("int");

                    b.Property<int>("Stamina")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<string>("Talents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.ResourceRecovery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CombatPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ResourceRecovery");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.ResourceRecoveryGeneral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageValue")
                        .HasColumnType("float");

                    b.Property<int>("CastNumber")
                        .HasColumnType("int");

                    b.Property<int>("CombatPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("MaxValue")
                        .HasColumnType("int");

                    b.Property<int>("MinValue")
                        .HasColumnType("int");

                    b.Property<double>("ResourcePerSecond")
                        .HasColumnType("float");

                    b.Property<string>("Spell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ResourceRecoveryGeneral");
                });

            modelBuilder.Entity("CombatAnalysis.DAL.Entities.SpecializationScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BossId")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("Heal")
                        .HasColumnType("int");

                    b.Property<int>("SpecId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("SpecializationScore");
                });
#pragma warning restore 612, 618
        }
    }
}
