env: Production
resources:
  cpu: 80
  memory: 80
service:
  port: 80
  targetPort: 8080
autoscaling:
  min: 3
  max: 6
user:
  name: user
  replicas: 3
  container:
    name: user
    image: solinx/combatanalysisuserapi
    port: 8080
  service:
    port: 80
    targetPort: 8080
  ingress:
    host: api.user.analysis.com
communication:
  name: communication
  replicas: 3
  container:
    name: communication
    image: solinx/combatanalysiscommunicationapi
    port: 8080
  service:
    port: 80
    targetPort: 8080
  ingress:
    host: api.communication.analysis.com
  vault:
    serviceAccountName: communication-sa
    role: communication-role
chat:
  name: chat
  replicas: 3
  container:
    name: chat
    image: solinx/combatanalysischatapi
    port: 8080
  service:
    port: 80
    targetPort: 8080
  ingress:
    host: api.chat.analysis.com
  vault:
    serviceAccountName: chat-sa
    role: chat-role
parser:
  name: combat-parser
  replicas: 3
  container:
    name: combat-parser
    image: solinx/combatanalysiscombatparserapi
    port: 8080
  service:
    port: 80
    targetPort: 8080
  ingress:
    host: api.parser.analysis.com
health:
  name: health
  replicas: 3
  container:
    name: health
    image: solinx/healthapi
    port: 8080
  service:
    port: 80
    targetPort: 8080
  ingress:
    host: health.analysis.com
