apiVersion: v1
kind: Secret
metadata:
  name: authentication
type: Opaque
data:
  ISSUER: aHR0cHM6Ly9pZGVudGl0eS5hbmFseXNpcy5jb20v
  ISSUER_SIGNIN_KEY: YUZvL1ArME04VFJLaGprSWhqUjErMVkvYjc3ZVNsOUV3ZGoyZTNoU3hSUT0=
  AUTHORITY: aHR0cHM6Ly9pZGVudGl0eS5hbmFseXNpcy5jb20v