apiVersion: batch/v1
kind: Job
metadata:
  name: vault-create-token
spec:
  template:
    spec:
      serviceAccountName: vault-init
      containers:
        - name: vault
          image: hashicorp/vault:1.15.4
          command:
            - /bin/sh
            - -c
            - |
              vault policy write admin-policy -<<EOF
              path "*" {
                  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }
              EOF

              RAW_OUTPUT=$(vault token create -policy=admin-policy)
              TOKEN=$(echo "$RAW_OUTPUT" | grep 'token ' | awk '{print $2}')
              vault kv put secret/bootstrap-token token=$TOKEN
              echo "Vault token: $TOKEN"
          envFrom:
            - secretRef:
                name: vault-init-secret
          volumeMounts:
            - name: vault-token
              mountPath: /vault-token
      volumes:
        - name: vault-token
          emptyDir: {}
      restartPolicy: OnFailure
