apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init-app-secrets
spec:
  template:
    spec:
      serviceAccountName: vault-init
      containers:
        - name: vault-init
          image: hashicorp/vault:1.15.4
          command:
            - /bin/sh
            - -c
            - |
              vault login $Token

              # Enable KV secret engine if not enabled
              vault secrets enable -path=app kv-v2 || echo "Secret engine 'app' already enabled"

              # Write default secrets for Clusters
              vault kv put app/Cluster/CombatParser CombatParser="http://api-combat-parser.api.svc.cluster.local/"
              vault kv put app/Cluster/User User="http://api-user.api.svc.cluster.local/"
              vault kv put app/Cluster/Chat Chat="http://api-chat.api.svc.cluster.local/"
              vault kv put app/Cluster/Communication Communication="http://api-communication.api.svc.cluster.local/"
              vault kv put app/Cluster/Identity Identity="http://identity.identity.svc.cluster.local/" 

              # Write default secrets for CORs
              vault kv put app/CORs/WebApp WebApp="https://encounters.analysis.com"

              # Write default secrets for Authentication app
              vault kv put app/Authentication/CookieDomain CookieDomain=".analysis.com"
              vault kv put app/Authentication/RedirectUri RedirectUri="encounters.analysis.com/callback"
              vault kv put app/Authentication/IdentityAuthPath IdentityAuthPath="authorization"
              vault kv put app/Authentication/IdentityRegistryPath IdentityRegistryPath="registration"
              vault kv put app/Authentication/CodeChallengeMethod CodeChallengeMethod="SHA-256"
              vault kv put app/Authentication/RefreshTokenExpiresDays RefreshTokenExpiresDays="7"
              vault kv put app/Authentication/GrantType/Code Code="code"
              vault kv put app/Authentication/GrantType/Authorization Authorization="authorizationCode"
              vault kv put app/Authentication/GrantType/RefreshToken RefreshToken="refreshToken"
              vault kv put app/Authentication/Client/ClientId ClientId="$WEB_CLIENT_ID"
              vault kv put app/Authentication/Client/Scope Scope="$SCOPE"
          envFrom:
            - secretRef:
                name: vault-init-secret
            - secretRef:
                name: web-client
      restartPolicy: OnFailure
