apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init-api-secrets
spec:
  template:
    spec:
      serviceAccountName: vault-init
      containers:
        - name: vault-init
          image: hashicorp/vault:1.15.4
          command:
            - /bin/sh
            - -c
            - |
              vault login $Token

              # Enable KV secret engine if not enabled
              vault secrets enable -path=api kv-v2 || echo "Secret engine 'api' already enabled"

              # Write default secrets for Kafka
              vault kv put api/Kafka/BootstrapServers BootstrapServers="kafka-service.msg-broker-1.svc.cluster.local:9092"
              vault kv put api/Kafka/Consumer/GroupId GroupId="combatParser"
              vault kv put api/Kafka/Consumer/AutoOffsetReset AutoOffsetReset="Earliest"
              
              # Write default secrets for API
              vault kv put api/API/Identity Identity="https://identity.analysis.com/"
              vault kv put api/API/User User="https://api.user.analysis.com/"

              # Write default secrets for Authentication API
              vault kv put api/Authentication/Issuer Issuer="$ISSUER"
              vault kv put api/Authentication/IssuerSigningKey IssuerSigningKey="$ISSUER_SIGNIN_KEY"
              vault kv put api/Authentication/Authority Authority="$AUTHORITY"
              vault kv put api/Authentication/Protocol Protocol="https"
              vault kv put api/Authentication/AccessTokenExpiresMins AccessTokenExpiresMins="60"
              vault kv put api/Authentication/RefreshTokenExpiresDays RefreshTokenExpiresDays="7"
              vault kv put api/Authentication/GrantType/Code Code="code"
              vault kv put api/Authentication/GrantType/Authorization Authorization="authorizationCode"
              vault kv put api/Authentication/GrantType/RefreshToken RefreshToken="refreshToken"
              vault kv put api/Authentication/Client/WebClientId WebClientId="$WEB_CLIENT_ID"
              vault kv put api/Authentication/Client/DesktopClientId DesktopClientId="$DESKTOP_CLIENT_ID"
              vault kv put api/Authentication/Client/Scope Scope="$SCOPE"

              # Write default secrets for Smtp
              vault kv put api/Smtp/Host Host="smtp.mail.ru"
              vault kv put api/Smtp/Port Port="587"
              vault kv put api/Smtp/EnableSsl EnableSsl="true"
              vault kv put api/Smtp/UseDefaultCredentials UseDefaultCredentials="false"
              vault kv put api/Smtp/DisplayName DisplayName="Combat Analysis"
              vault kv put api/Smtp/Email Email="yaneznau90@mail.ru"
              vault kv put api/Smtp/Password Password="$APP_PASSWORD"

              # Write default secrets for Chat API
              vault kv put api/DB/Chat/DefaultConnection DefaultConnection="$CHAT_DEFAULT_CONNECTION"
              vault kv put api/DB/Chat/FirebaseConnection FirebaseConnection="$CHAT_FIREBASE_CONNECTION"
              vault kv put api/DB/Chat/Name Name="MSSQL"

              # Write default secrets for Communication API
              vault kv put api/DB/Communication/DefaultConnection DefaultConnection="$COMMUNICATION_DEFAULT_CONNECTION"
              vault kv put api/DB/Communication/FirebaseConnection FirebaseConnection="$COMMUNICATION_FIREBASE_CONNECTION"
              vault kv put api/DB/Communication/Name Name="MSSQL"
              
              # Write default secrets for User API
              vault kv put api/DB/User/DefaultConnection DefaultConnection="$USER_DEFAULT_CONNECTION"
              vault kv put api/DB/User/FirebaseConnection FirebaseConnection="$USER_FIREBASE_CONNECTION"
              vault kv put api/DB/User/Name Name="MSSQL"

              # Write default secrets for Combat parser API
              vault kv put api/DB/Parser/DefaultConnection DefaultConnection="$PARSER_DEFAULT_CONNECTION"
              vault kv put api/DB/Parser/FirebaseConnection FirebaseConnection="$PARSER_FIREBASE_CONNECTION"
              vault kv put api/DB/Parser/Name Name="MSSQL"
              vault kv put api/DB/Parser/DataProcessingType DataProcessingType="StoredProcedure"
              vault kv put api/DB/Parser/CommandTimeout CommandTimeout="180"
              vault kv put api/DB/Parser/MaxRequestBodySize MaxRequestBodySize="150000000"

              # Write default secrets for Identity
              vault kv put api/DB/Identity/DefaultConnection DefaultConnection="$IDENTITY_DEFAULT_CONNECTION"
              vault kv put api/DB/Identity/Name Name="MSSQL"
          envFrom:
            - secretRef:
                name: vault-init-secret
            - secretRef:
                name: authentication
            - secretRef:
                name: client
            - secretRef:
                name: chat-database
            - secretRef:
                name: communication-database
            - secretRef:
                name: user-database
            - secretRef:
                name: parser-database
            - secretRef:
                name: identity-database
            - secretRef:
                name: smtp-connection
      restartPolicy: OnFailure
