apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init-base-secrets
spec:
  template:
    spec:
      serviceAccountName: vault-init
      containers:
        - name: vault-init
          image: hashicorp/vault:1.15.4
          command:
            - /bin/sh
            - -c
            - |
              vault login $Token

              # Enable KV secret engine if not enabled
              vault secrets enable -path=api kv-v2 || echo "Secret engine already enabled"

              # Write default secrets
              vault kv put api/Kafka/BootstrapServers BootstrapServers="kafka-service.msg-broker-1.svc.cluster.local:9092"
              vault kv put api/Kafka/Consumer/GroupId GroupId="combatParser"
              vault kv put api/Kafka/Consumer/AutoOffsetReset AutoOffsetReset="Earliest"

              vault kv put api/DB/Chat/DefaultConnection DefaultConnection="$CHAT_DEFAULT_CONNECTION"
              vault kv put api/DB/Chat/FirebaseConnection FirebaseConnection="$CHAT_FIREBASE_CONNECTION"
              vault kv put api/DB/Chat/Name Name="MSSQL"

              vault kv put api/DB/Communication/DefaultConnection DefaultConnection="$COMMUNICATION_DEFAULT_CONNECTION"
              vault kv put api/DB/Communication/FirebaseConnection FirebaseConnection="$COMMUNICATION_FIREBASE_CONNECTION"
              vault kv put api/DB//CommunicationName Name="MSSQL"

              vault kv put api/API/Identity Identity="https://identity.analysis.com/"

              vault kv put api/Authentication/Issuer Issuer="$ISSUER"
              vault kv put api/Authentication/IssuerSigningKey IssuerSigningKey="$ISSUER_SIGNIN_KEY"
              vault kv put api/Authentication/Authority Authority="$AUTHORITY"
              vault kv put api/Authentication/Client/WebClientId WebClientId="$WEB_CLIENT_ID"
              vault kv put api/Authentication/Client/DesktopClientId DesktopClientId="$DESKTOP_CLIENT_ID"
              vault kv put api/Authentication/Client/Scope Scope="$SCOPE"
          envFrom:
            - secretRef:
                name: vault-init-secret
            - secretRef:
                name: authentication
            - secretRef:
                name: client
            - secretRef:
                name: chat-database
            - secretRef:
                name: communication-database
      restartPolicy: OnFailure
