apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    env: {{ .Values.env }}
    owner: OlegFedosov
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "{{ .Values.vault.role }}"
        vault.hashicorp.com/agent-inject-secret-api: "api/API"
        vault.hashicorp.com/agent-inject-template-api: |
          {{ "{{" }} with secret "api/API/Identity" {{ "}}" }}
          export API__Identity="{{ "{{" }} .Data.data.Identity {{ "}}" }}"
          {{ "{{" }} end{{ "}}" }}
        vault.hashicorp.com/agent-inject-secret-db: "api/DB"
        vault.hashicorp.com/agent-inject-template-db: |
          {{ "{{" }} with secret "api/DB/Identity/DefaultConnection " {{ "}}" }}
          export Database__DefaultConnection="{{ "{{" }} .Data.data.DefaultConnection {{ "}}" }}"
          {{ "{{" }} end{{ "}}" }}
        vault.hashicorp.com/agent-inject-secret-authentication: "api/Authentication"
        vault.hashicorp.com/agent-inject-template-authentication: |
          {{ "{{" }} with secret "api/Authentication/Authority" {{ "}}" }}
          export Authentication__Authority="{{ "{{" }} .Data.data.Authority {{ "}}" }}"
          {{ "{{" }} end{{ "}}" }}
          {{ "{{" }} with secret "api/Authentication/Issuer  " {{ "}}" }}
          export Authentication__Issuer="{{ "{{" }} .Data.data.Issuer {{ "}}" }}"
          {{ "{{" }} end{{ "}}" }}
          {{ "{{" }} with secret "api/Authentication/IssuerSigningKey" {{ "}}" }}
          export Authentication__IssuerSigningKey="{{ "{{" }} .Data.data.IssuerSigningKey {{ "}}" }}"
          {{ "{{" }} end{{ "}}" }}
          {{ "{{" }} with secret "api/Authentication/Client/DesktopClientId" {{ "}}" }}
          export Authentication__Client__DesktopClientId="{{ "{{" }} .Data.data.DesktopClientId {{ "}}" }}"
          {{ "{{" }} end{{ "}}" }}
          {{ "{{" }} with secret "api/Authentication/Client/WebClientId   " {{ "}}" }}
          export Authentication__Client__WebClientId="{{ "{{" }} .Data.data.WebClientId  {{ "}}" }}"
          {{ "{{" }} end{{ "}}" }}
          {{ "{{" }} with secret "api/Authentication/Client/Scope " {{ "}}" }}
          export Authentication__Client__Scope="{{ "{{" }} .Data.data.Scope  {{ "}}" }}"
          {{ "{{" }} end{{ "}}" }}
    spec:
      serviceAccountName: {{ .Values.vault.serviceAccountName }}
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.imageTags.health.health }}
          command:
            ['sh', '-c']
          args:
            ['. /vault/secrets/api && . /vault/secrets/db && . /vault/secrets/authentication && dotnet HealthAPI.dll']
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
           - name: ASPNETCORE_ENVIRONMENT
             value: {{ .Values.env }}