apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init-base-secrets
spec:
  template:
    spec:
      serviceAccountName: vault-init
      containers:
        - name: vault-init
          image: hashicorp/vault:1.15.4
          command:
            - /bin/sh
            - -c
            - |
              vault login $Token

              vault policy write chat-app-policy -<<EOF
              path "api/*" {
                capabilities = ["read"]
              }
              EOF

              # Enable KV secret engine if not enabled
              vault secrets enable -path=api kv-v2 || echo "Secret engine already enabled"

              # Write default secrets
              vault kv put api/Kafka/BootstrapServers BootstrapServers="kafka-service.msg-broker-1.svc.cluster.local:9092"
              vault kv put api/DB/Name Name="MSSQL"
              vault kv put api/API/Identity Identity="https://identity.analysis.com/"

              # Enable Kubernetes auth
              vault auth enable kubernetes

              # Write auth Kubernetes role for chat api
              vault write auth/kubernetes/role/chat-role bound_service_account_names=chat-sa bound_service_account_namespaces=api policies=chat-app-policy ttl=24h
              
              # Write auth Kubernetes config
              vault write auth/kubernetes/config token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443" kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          envFrom:
            - secretRef:
                name: vault-init-secret
      restartPolicy: OnFailure
