apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.kafka.name }}-ingress
spec:
  tls:
  - hosts:
      - {{ .Values.kafka.ingress.host }}
    secretName: tls-secret
  rules:
  - host: {{ .Values.kafka.ingress.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.kafka.name }}-service
              port:
                number: {{ .Values.kafka.service.port }}