apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.zookeeper.name }}
  labels:
    app: {{ .Release.Name }}
    env: {{ .Values.env }}
    owner: OlegFedosov
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.zookeeper.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.zookeeper.name }}
    spec:
      containers:
        - name: {{ .Values.zookeeper.container.name }}
          image: {{ .Values.zookeeper.container.image }}:{{ .Values.imageTags.msgBroker.zookeeper }}
          ports:
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
              