apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-{{ .Values.zookeeper.name }}
spec:
  scaleTargetRef:
    apiVersion: msg-broker/v1
    kind: Deployment
    name: {{ .Release.Name }}-{{ .Values.zookeeper.name }}
  minReplicas: {{ .Values.autoscaling.min }}
  maxReplicas:  {{ .Values.autoscaling.max }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.resources.cpu }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.resources.memory }}